export const LOGIN_INPUT = 'loginInput'
export const SIGNUP_INPUT = 'signupInput'
export const UPDATE_USER_INPUT = 'updateUserInput'
export const USER_IDS = 'userIds'
export const COOKIE_NAME = 'cookie'
