#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yellow='\033[0;33m'
no_color='\033[0m'

# To fix color issues
exec >/dev/tty 2>&1

echo -e "\n${yellow}Linting & Spell Checking:${no_color}"
FORCE_COLOR=1 pnpm turbo run spell-check lint

echo -e "${yellow}Formatting:${no_color}"
FORCE_COLOR=1 pnpm exec lint-staged


